#' Execute Kagi API requests and save JSON responses
#'
#' Execute one or more `rkagi` query objects against the Kagi API and write
#' raw JSON responses to disk. This function supports search, enrich (web/news),
#' and summarize query classes generated by [search_query()],
#' [enrich_web_query()], [enrich_news_query()], and [summarize_query()].
#'
#' If `query` is a list of query objects, requests are executed in parallel
#' (using `workers`) and each query is written into a named subdirectory under
#' `output`.
#'
#' @param connection A [kagi_connection()] object.
#' @param query A query object of class `kagi_search_query`,
#'   `kagi_summarize_query`, `kagi_enrich_web_query`, `kagi_enrich_news_query`,
#'   or a list of such objects.
#' @param limit Optional integer limit used for search and enrich endpoints.
#' @param output Directory where JSON response files are written.
#' @param overwrite Logical. If `TRUE`, existing `output` is deleted before
#'   writing.
#' @param append Logical. If `TRUE`, write into an existing `output` directory
#'   instead of deleting it.
#' @param workers Number of parallel workers to use when `query` is a list.
#' @param verbose Logical indicating whether progress messages should be shown.
#'
#' @return The normalized path to `output`.
#'
#' @details
#' Files are written as `{endpoint}_{page}.json` (for example `search_1.json`).
#' Pagination is handled via `meta$next_cursor` when provided by the API.
#'
#' @md
#'
#' @importFrom utils tail
#' @importFrom httr2 req_url_query req_perform resp_body_json resp_body_string
#' @importFrom utils packageVersion
#' @importFrom future plan multisession sequential
#' @importFrom future.apply future_lapply
#'
#' @export
#'
kagi_request <- function(
  connection,
  query,
  limit = NULL,
  output = NULL,
  overwrite = FALSE,
  append = FALSE,
  workers = 1,
  verbose = FALSE
) {
  # Helper function -------------------------------------------------------

  output_check <- function(output, overwrite, append, verbose) {
    if (dir.exists(output)) {
      if (!overwrite & !append) {
        stop(
          "Directory ",
          output,
          " exists.\n",
          "Either specify `overwrite = TRUE` , `append = TRUE` or delete it."
        )
      }
      if (!append) {
        if (verbose) {
          message(
            "Deleting and recreating `",
            output,
            "` to avoid inconsistencies."
          )
        }
      } else {
        if (verbose) {
          message(
            "Appending to existing files in `",
            output,
            "`."
          )
        }
        return(output)
      }
      unlink(output, recursive = TRUE)
    }
  }

  # uargument check ------------------------------------------------------------

  if (!inherits(connection, "kagi_connection")) {
    stop("`connection` must be of class `kagi_connection`.")
  }

  if (
    !inherits(
      query,
      c(
        "kagi_search_query",
        "kagi_summarize_query",
        "kagi_enrich_web_query",
        "kagi_enrich_news_query",
        "list"
      )
    )
  ) {
    stop(
      "`query` must be of class `kagi_search_query`, `kagi_summarize_query` or `list` of such objects."
    )
  }

  # Call for each element if query is a list ---------------------------

  if (
    !inherits(
      query,
      c(
        "kagi_search_query",
        "kagi_summarize_query",
        "kagi_enrich_web_query",
        "kagi_enrich_news_query"
      )
    )
  ) {
    future::plan(future::multisession, workers = workers)

    on.exit(
      future::plan(future::sequential),
      add = TRUE
    )

    output_check(output, overwrite, append, verbose)

    result <- future.apply::future_lapply(
      seq_along(query),
      function(i) {
        nm <- names(query)[i]
        if (is.null(nm)) {
          nm <- paste0("query_", i)
        }
        kagi_request(
          connection = connection,
          query = query[[i]],
          limit = limit,
          output = file.path(output, nm),
          overwrite = FALSE,
          append = TRUE,
          verbose = verbose
        )
      },
      future.seed = TRUE
    )
    return(output)
  } else {
    # Argument Checks --------------------------------------------------------

    if (is.null(output)) {
      stop("No `output` output specified!")
    }

    output_check(output, overwrite, append, verbose)

    # Preparations -----------------------------------------------------------

    dir.create(output, recursive = TRUE, showWarnings = FALSE)

    output <- normalizePath(output)

    req <- switch(
      class(query)[[1]],
      kagi_search_query = {
        endpoint <- "search"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_url_query(
            q = query,
            limit = limit
          )
      },
      kagi_summarize_query = {
        endpoint <- "summarize"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_headers(
            "Content-Type" = "application/json"
          ) |>
          httr2::req_body_json(
            as.list(
              query
            )
          )
      },
      kagi_enrich_web_query = {
        endpoint <- "enrich/web"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_url_query(
            q = query,
            limit = limit
          )
      },
      kagi_enrich_news_query = {
        endpoint <- "enrich/news"
        connection |>
          httr2::req_url_path_append(endpoint) |>
          httr2::req_url_query(
            q = query,
            limit = limit
          )
      },
      stop("Unknown Query Class: ", class(query))
    )

    req <- req |>
      httr2::req_user_agent(
        paste(
          "rkagi v",
          packageVersion("rkagi")
        )
      )

    if (verbose) {
      message("Request:\n")
      message("URL: ", req$url)
      message("\n")
    }

    # Remove empty query parameters

    # Initialize results and page counter
    page <- 1

    # Pagination loop
    repeat {
      if (verbose) {
        message("\nDownloading page ", page)
        NULL
      }

      resp <- req_perform(req)

      data <- resp |>
        httr2::resp_body_json()

      resp |>
        httr2::resp_body_string() |>
        writeLines(
          con = file.path(
            output,
            paste0(gsub("/", "_", endpoint), "_", page, ".json")
          )
        )

      ## This always breaks and nneeds to be adjusted for the new API!
      if (is.null(data$meta$next_cursor)) {
        break
      }

      req <- req |>
        httr2::req_url_query(cursor = data$meta$next_cursor)

      page <- page + 1
    }
    ###

    return(output)
  }
}
